### PR TITLE
feat: backend (part 2)

### PR DESCRIPTION
**Pull request by charsleysa**
More functionality moved to firebase functions
Begin using split stores for views

### CODE REVIEW

**Comment by charsleysa** [comment]
@tairea I've pushed up a fix, try giving it another go

**Comment by tairea** [comment]
another error on load...
image

**Comment by charsleysa** [comment]
Looks like there was an issue with your login, possibly internet connection issues, try refreshing the page.

**Comment by tairea** [comment]
> Looks like there was an issue with your login, possibly internet connection issues, try refreshing the page.

This is for loading without signing in. so public, no account yet.

**Comment by charsleysa** [comment]
@tairea I pushed up a fix for public loading when not logged in

**Review by tairea — APPROVED** [review]
alot of great improvements here. thanks @charsleysa 👏

**Pull request merged**
